services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf/mariadb-server.cnf:/etc/my.cnf.d/mariadb-server.cnf:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h mariadb -u $${DB_USER} -p$${DB_PASSWORD} --silent"]
      interval: 3s
      timeout: 3s
      retries: 30

    networks: [inception]

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks: [inception]

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on: [wordpress]
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/ssl:/etc/nginx/ssl:ro
    networks: [inception]


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/data/wordpress"

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/data/mariadb"

networks:
  inception:
    driver: bridge
