services:
  mariadb:
    # build: ./requirements/mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks: [inception]
    command: ["sleep", "infinity"]

  wordpress:
    # build: ./requirements/wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    depends_on: [mariadb]
    volumes:
      - wordpress_data:/var/www/html
    networks: [inception]
    command: ["sleep", "infinity"]

  nginx:
    # build: ./requirements/nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    depends_on: [wordpress]
    ports:
      - "${HTTPS_PORT}:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks: [inception]
    command: ["sleep", "infinity"]

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "~/data/wordpress"

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "~/data/mariadb"

networks:
  inception:
    name: inception